### ISSUE TITLE
availability of your MS thesis

### ISSUE THREAD

**Issue by kaishijeng** [dgschwend/zynqnet#1]
Hi,

  Is your thesis publicly available? If yes, can you show me a download link?

Thanks,

**Comment by dgschwend** [comment]
Hi kaishijeng

Thanks for your interest. I'm currently finishing the written report, and I plan to upload it to Github towards the middle of August.
I'll add a corresponding note to the README, didn't think anyone would stumble upon the repository so soon... :)

Best regards,
David

**Comment by kaishijeng** [comment]
David

   Thanks for an update

**Comment by kaishijeng** [comment]
Do we still plan to release the report in this month?

Thanks

**Comment by dgschwend** [comment]
Hi @kaishijeng. I finally got all the necessary permissions for publication. You can find the whole Master Thesis including all source code, generated files, as well as the Project Report in the repository.

**Comment by kaishijeng** [comment]
David

  Thanks for letting me know your report is available.


FC
