### ISSUE TITLE
Having some quesions about  files in  _HLS_CODE and _FIRMWARE

### ISSUE THREAD

**Issue by liwei1018** [dgschwend/zynqnet#10]
Hi David,
 I was using vivado HLS for the first time. I have some simple questions. cpu_top.cpp  file in _HLS_CODE folder is not testbench ? and are those files in _FIRMWARE folder Compiled with SDK? is it the application is run on the board without linux or not ? I am look forward to your help. thanks.

**Comment by dgschwend** [comment]
Hi liwei1018
* cpu_top.cpp is the test bench, that's correct.
* the files in _FIRMWARE can be compiled with the Xilinx SDK or any other compiler for the ARM core.
* the application is run under Linux.
Regards, David
