### ISSUE TITLE
Conversion to System C

### ISSUE THREAD

**Issue by wasim6691** [dgschwend/zynqnet#21]
Hi David. Hope You are fine and doing well. 

I am the beginner in System C. Can You please help me out that How to convert Your ZYNQNET C++ code into System C. Can You give me few tips. I would be highly thankful for that. Waiting for the reply. Thanks 

Best Regards
Wasim Khan

**Comment by dgschwend** [comment]
Sorry, I dont‘have any experience in SystemC.
