### ISSUE TITLE
DEBUGGING the Code

### ISSUE THREAD

**Issue by wasim6691** [dgschwend/zynqnet#27]
Hi David

Hope You are fine. I have to ask You that can we compile and Debug  Your code on a c++ compiler besides VIVADO HLS. I really want to debug your code to understand it fully. Thanks. waiting for Your reply

Khan
Master thesis student at Bosch, Reningen.

**Comment by chengsonghust** [comment]
Vivado HLS can easily debug the code step by step. Other c++ compiler maybe unable to handle #pragma directives.

**Comment by wasim6691** [comment]
Which Fpga should I select in the vivado Open Project. I am encountering an
error when I run the project. I send u the exact error in some time.

**Comment by dgschwend** [comment]
Most FPGAs should work. Original work is on XCZ7045. See the project report for details.
