### ISSUE TITLE
Problem with loadbit command

### ISSUE THREAD

**Issue by radwrob** [dgschwend/zynqnet#3]
I have a problem with the instruction 'loadbit' from _RUN.sh script. How to use this command to program the FPGA?

**Comment by dgschwend** [comment]
It's a proprietary tool on the SCS Zynq Box for programming a new bitstream onto the PL. As an alternative, the bitstream can be loaded via the First Stage Bootloader. If you generate your own Zynq Linux System with Xilinx SDK, this happens automatically.
