### ISSUE TITLE
About the Linux Operating System on board

### ISSUE THREAD

**Issue by JackChenofNCP** [dgschwend/zynqnet#47]
Hi David, I read something about the Linux Operating System on Board in your report which I can't understand well.
Quoting : "However, the Zynqbox already runs a fully working and properly tested Linux installation and includes tools to load new bitstreams into the programmable logic. Due to lack of time, we strongly favored reusing this existing installation."
I am wondering how you "load new bitstreams into the PL" because I build a new linux system with a new boot.bin for reconfiguring PL every time to test a new bitstream after making some change and that didn't go well. So if you have some way to configure PL directly in the linux on board, dose that mean any working linux system can easily test the Accelerator by a simple command like "load bitstram"? Can you please explain to me how to that? Thanks a lot.

**Comment by dgschwend** [comment]
That‘s completely right. There are methods for loading new bitstreams from a running Linux (you can search the Internet for details). The Zynqbox (https://www.scs.ch/en/fpgabox.html) includes a command „load_bit“ which does exactly that. No need to rebuild Linux, no need to reboot.

**Comment by JackChenofNCP** [comment]
Thanks, I have found the way to do that. It helps a lot.
