### ISSUE TITLE
Testbench with a stream image file in HLS

### ISSUE THREAD

**Issue by maurimum** [dgschwend/zynqnet#6]
Hello, currently I'm working in a project that focus in a based on zynqnet CNN accelerator, the tool that used is Vivado HLS, any advices for creating an IP that has a stream image for run a testbench that simulate the CPU tasks(reading an image and processing the last layer results) and calls the IP accelerator?  Thanks!

**Comment by dgschwend** [comment]
Sorry, I don't really understand your question. With Vivado HLS, you write the testbench in C/C++, so you can actually run your CPU tasks directly and call your accelerator block from there. No need to write a separate testbench and "simulate the CPU tasks".
Regarding "stream images", do you refer to an AXI stream interface? I don't have much experience with that.
