### ISSUE TITLE
Minimum Requirements and Details of the board

### ISSUE THREAD

**Issue by amnamasood** [dgschwend/zynqnet#7]
Hello!
We are trying to implement this project for some image recognition task. Can you please provide us the specific details of the boards that you used for this implementation and the minimum requirements of FPGA needed for this project?

**Comment by dgschwend** [comment]
Have you read the project documentation? FPGA ressource requirements are on p. 63, the Zynqbox specs are on p. 31. What part of it did you not understand? 

––
David Gschwend • +41 79 552 74 00 • Winkelriedstr. 56 • 6003 Luzern

**Comment by amnamasood** [comment]
Yes I read that but I was not clear on them as I am new to FPGAs, and XC7Z045 is also quite expensive. Sorry for your inconvenience.
