### ISSUE TITLE
Having some quesions about implementing the net for different task.

### ISSUE THREAD

**Issue by UV-ETSE-GPDS** [dgschwend/zynqnet#9]
Hi David,
I'm curious if you continue your work on CNN. I am currently dealing with several issues regarding FPGA implementation of Squeezenet and maybe you can help with it.

**Comment by dgschwend** [comment]
Hi UV-ETSE-GPDS,
I am still working on CNNs and with FPGAs in general, but currently not on this project. Sure, feel free to ask questions here, I'll see if I can help.

**Comment by dgschwend** [comment]
???
